import { CaseProps } from "@/types";

export const dummyCases: Array<CaseProps> = [
  {
    username: "SimonX",
    application_date: new Date("2024-04-13"), // YYYY-MM-DD format
    application_status: "Submitted",
    biometric_status: "Completed",
    biometric_date: new Date("2024-04-15"),
    medical_status: "Passed",
    medical_date: new Date("2024-04-17"),
    elegibility_status: "Completed",
    elegibility_date: new Date("2024-04-31"),
    background_check_status: "Completed",
    background_check_date: new Date("2024-04-21"),
    pPR_request: "Yes",
  },
  {
    username: "JohnDoe123",
    application_date: new Date("2024-05-03"),
    application_status: "In Progress",
    biometric_status: "Submitted",
    biometric_date: new Date("2024-05-06"),
    medical_status: "Pending",
    medical_date: new Date("2024-05-03"), // Remains null
    elegibility_status: "Submitted",
    elegibility_date: new Date("2024-05-03"), // Remains null
    background_check_status: "Not Started",
    background_check_date: new Date("2024-05-03"), // Remains null
    pPR_request: "No",
  },
  {
    username: "AliceWonder",
    application_date: new Date("2024-05-03"),
    application_status: "Submitted",
    biometric_status: "Completed",
    biometric_date: new Date("2024-05-03"),
    medical_status: "Passed",
    medical_date: new Date("2024-05-03"),
    elegibility_status: "In Progress",
    elegibility_date: new Date("2024-05-03"),
    background_check_status: "Submitted",
    background_check_date: new Date("2024-05-03"),
    pPR_request: "Yes",
  },
  {
    username: "BobBuilder10",
    application_date: new Date("2024-04-27"),
    application_status: "Completed",
    biometric_status: "Completed",
    biometric_date: new Date("2024-04-30"),
    medical_status: "Passed",
    medical_date: new Date("2024-05-10"),
    elegibility_status: "Completed",
    elegibility_date: new Date("2024-04-24"), // Corrected invalid date
    background_check_status: "Completed",
    background_check_date: new Date("2024-05-01"),
    pPR_request: "No",
  },
  {
    username: "TechSavvy",
    application_date: new Date("2024-05-01"),
    application_status: "Submitted",
    biometric_date: new Date("2024-04-30"),
    biometric_status: "Not Started",
    medical_status: "N/A",
    medical_date: new Date("2024-05-10"), // Remains null
    elegibility_status: "N/A",
    elegibility_date: new Date("2024-05-10"), // Remains null
    background_check_status: "N/A",
    background_check_date: new Date("2024-05-10"), // Remains null
    pPR_request: "Yes",
  },
  {
    username: "CharlieBravo",
    application_date: new Date("2024-04-20"),
    application_status: "Submitted",
    biometric_status: "Pending",
    biometric_date: new Date("2024-04-25"),
    medical_status: "In Progress",
    medical_date: new Date("2024-04-29"),
    elegibility_status: "Not Started",
    elegibility_date: new Date("2024-05-15"),
    background_check_status: "Not Started",
    background_check_date: new Date("2024-05-15"),
    pPR_request: "No",
  },
  {
    username: "DavidTango",
    application_date: new Date("2024-03-15"),
    application_status: "Completed",
    biometric_status: "Completed",
    biometric_date: new Date("2024-03-20"),
    medical_status: "Passed",
    medical_date: new Date("2024-03-27"),
    elegibility_status: "Completed",
    elegibility_date: new Date("2024-04-05"),
    background_check_status: "Completed",
    background_check_date: new Date("2024-04-10"),
    pPR_request: "Yes",
  },
  {
    username: "EchoRomeo",
    application_date: new Date("2024-04-01"),
    application_status: "In Progress",
    biometric_status: "Completed",
    biometric_date: new Date("2024-04-08"),
    medical_status: "Passed",
    medical_date: new Date("2024-04-12"),
    elegibility_status: "In Progress",
    elegibility_date: new Date("2024-04-20"),
    background_check_status: "Submitted",
    background_check_date: new Date("2024-04-27"),
    pPR_request: "No",
  },
  {
    username: "FoxtrotZulu",
    application_date: new Date("2024-05-02"),
    application_status: "Submitted",
    biometric_date: new Date("2024-04-30"),
    biometric_status: "Not Started",
    medical_status: "Pending",
    medical_date: new Date("2024-05-17"),
    elegibility_status: "N/A",
    elegibility_date: new Date("2024-05-17"), // Remains null
    background_check_status: "N/A",
    background_check_date: new Date("2024-05-17"), // Remains null
    pPR_request: "Yes",
  },
  {
    username: "GolfAlpha",
    application_date: new Date("2024-04-10"),
    application_status: "Completed",
    biometric_status: "Completed",
    biometric_date: new Date("2024-04-15"),
    medical_status: "Passed",
    medical_date: new Date("2024-04-22"),
    elegibility_status: "Completed",
    elegibility_date: new Date("2024-04-25"),
    background_check_status: "Completed",
    background_check_date: new Date("2024-04-30"),
    pPR_request: "No",
  },
];
